# Generated by Django 5.1 on 2024-09-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
