# Generated by Django 5.1.2 on 2024-10-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
