# Generated by Django 5.1.2 on 2024-10-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
