# Generated by Django 4.2.13 on 2024-07-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becholer',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('mail', models.EmailField(max_length=254)),
                ('max_budget', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='becholer')),
                ('addr', models.CharField(max_length=50)),
                ('sugg', models.CharField(max_length=50)),
            ],
        ),
    ]
