# Generated by Django 4.2.13 on 2024-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('oid', models.BigAutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=20)),
                ('gimage', models.ImageField(null=True, upload_to='wedding')),
                ('bimage', models.ImageField(null=True, upload_to='wedding')),
                ('mail', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('max_budget', models.FloatField()),
                ('venue', models.CharField(max_length=30)),
                ('sugg', models.CharField(max_length=50)),
            ],
        ),
    ]
