# Generated by Django 4.2.13 on 2024-07-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0003_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wedding',
            name='date',
            field=models.DateField(default='DD-MM-YYYY'),
        ),
    ]
