# Generated by Django 5.1.2 on 2024-10-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0004_alter_wedding_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='becholer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='bimage',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='gimage',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='bimage',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='gimage',
        ),
        migrations.AddField(
            model_name='becholer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reception',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wedding',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
