# Generated by Django 5.1.2 on 2024-10-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0005_remove_becholer_image_remove_reception_bimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='becholer',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='becholer',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='reception',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reception',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='wedding',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wedding',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
