# Generated by Django 5.1.2 on 2024-10-24 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0006_becholer_invoice_sent_becholer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='becholer',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 24, 11, 47, 17, 927207, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='becholer',
            name='theme_name',
            field=models.CharField(default=datetime.datetime(2024, 10, 24, 11, 47, 41, 416873, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='becholer',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
