# Generated by Django 5.1.2 on 2024-10-24 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0007_becholer_booked_at_becholer_theme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 24, 12, 48, 51, 867009, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 24, 12, 48, 56, 725360, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reception',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='max_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
